name: "test pr"
on:
  pull_request:

jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          repo_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          imgur_client_id: ${{ secrets.IMGUR_CLIENT_ID }}
